oauth2_provider/oauth2_validators.py

The previous code broke OAuthLib when `rotate_refresh_token()` returned `False`. OAuthLib would attempt to serialize the `RefreshToken` object into JSON (it is supposed to be a string).
[This](https://github.com/idan/oauthlib/blob/96dc15143ef3baff66231711d33f4d5c6eb94f7b/oauthlib/oauth2/rfc6749/grant_types/refresh_token.py#L97-L98) is where the `refresh_token` gets replaced by oauth-toolkit, and [this](https://github.com/idan/oauthlib/blob/20d6640a7c8eadc4b5af15895c1358b868a02464/oauthlib/oauth2/rfc6749/tokens.py#L225) is where it breaks OAuthLib.

Do not override internal OAuthLib property

---

docs/rest-framework/getting_started.rst

I've removed <client_id> and <client_secret> from the "url" because it could have symbols like "!" and "@" wich makes curl not work ok, so I've used the -u flag to pass the client_di and secret between quotes.

Improving curl example

---

AUTHORS
oauth2_provider/__init__.py
oauth2_provider/http.py
oauth2_provider/settings.py
oauth2_provider/tests/test_authorization_code.py
oauth2_provider/tests/test_validators.py
oauth2_provider/validators.py
oauth2_provider/views/base.py

As per [#154](https://github.com/evonove/django-oauth-toolkit/issues/154).

Allow custom uri schemes

---

docs/advanced_topics.rst
docs/conf.py
docs/settings.rst
docs/settings_generator.py

Fixes #109.
The directive can be rendered as a table or a definition list (I prefer the output of the latest so I put this one in  ``settings.rst``).
I wrote a short description of each setting, maybe you should review these before merging. There are written in ``docs/settings_generator.py``.

[docs] Added a REsT directive to generate the setting definition list

---

AUTHORS
oauth2_provider/oauth2_validators.py
oauth2_provider/tests/test_oauth2_validators.py

django-oauth-toolkit 0.7.2 contains three valunarabilitis on Basic authentication process. 
* It will raise IndexError when authentication header contains more than two white spaces. 
* It will raise TypeError when auth_string can't be decoded as base64.
* It will raise UnicodeDecodeError when base64 decoded auth_string can't be decoded as unicode by specified encoding.

Fixed valunarabilities on Basic authentication. 

---

oauth2_provider/oauth2_backends.py

On Python 2, passing unicode as the second argument to urllib.quote is a very bad idea - http://bugs.python.org/issue23885
On Python 3, both b'' and '' are fine.

Pass str/bytes instead of unicode/str to urllib.quote

---

README.rst
docs/changelog.rst
docs/settings.rst
oauth2_provider/oauth2_backends.py
oauth2_provider/settings.py
oauth2_provider/tests/test_client_credential.py
oauth2_provider/tests/test_mixins.py
oauth2_provider/tests/test_oauth2_backends.py
oauth2_provider/views/base.py
oauth2_provider/views/generic.py
oauth2_provider/views/mixins.py

Developers can configure the ``oauthlib_backend_class`` used by ``OAuthLibMixin``. DOT generic views retrieve the ``oauthlib_backend_class`` instance through the ``OAUTH2_BACKEND_CLASS`` settings which is defaulted to ``oauth2_provider.oauth2_backends.OAuthLibCore``.
In this way, the RFC compliant ``OAuthLibCore`` class is used as a default, while developers can create or extend new implementations.
The ``oauth2_provider.oauth2_backends.JSONOAuthLibCore`` is provided and using it as a backend class, solves the issue #127. This approach accepts POST request using the ``application/json`` ``Content-Type`` for all token endpoints.
Before merging this PR we should:
* code review provided tests
* choose in which part of the documentation add the ``JSONOAuthLibCore`` example

oauthlib_backend_class is now pluggable through Django settings

---

oauth2_provider/views/mixins.py

This checks for the presence of a question mark in the URI and changes the separator accordingly so as to not put two questions marks in the URI.
fixes #238

wrong exception is sent due to separator being hard coded to "?" when raising an error

---

.travis.yml
README.rst
oauth2_provider/tests/test_client_credential.py
oauth2_provider/tests/test_decorators.py
oauth2_provider/tests/test_mixins.py
oauth2_provider/tests/test_models.py
tox.ini

This PR adds Django 1.8 to the test matrix and makes the necessary updates to keep the tests passing. It doesn't seem like any changes to the package code are necessary, just tests.

support/test django 1.8

---

oauth2_provider/migrations/0001_initial.py
oauth2_provider/migrations/0002_08_updates.py

This splits the Django (non-South) migrations to ease the upgrade from 0.7.2 to 0.8.1+.
With this in place, one can fake the 0001 migration and then migrate to 0002 correctly, resulting in a correctly migrated app.

Fix the migrations to be two-step and allow upgrade from 0.7.2

---

docs/rest-framework/permissions.rst
oauth2_provider/ext/rest_framework/__init__.py
oauth2_provider/ext/rest_framework/permissions.py
oauth2_provider/tests/test_rest_framework.py
requirements/testing.txt

I think it's a great feature, the idea in this pull request is working like the [github scopes](https://developer.github.com/v3/oauth/#scopes).
About mock library, I've opened a [pull request in mock repo](https://github.com/testing-cabal/mock/pull/265).

Generic read write scope by resource

---

.travis.yml
oauth2_provider/compat.py
oauth2_provider/compat_handlers.py
oauth2_provider/templates/oauth2_provider/application_confirm_delete.html
oauth2_provider/templates/oauth2_provider/application_detail.html
oauth2_provider/templates/oauth2_provider/application_form.html
oauth2_provider/templates/oauth2_provider/application_list.html
oauth2_provider/templates/oauth2_provider/application_registration_form.html
oauth2_provider/templatetags/compat.py
oauth2_provider/tests/settings.py
oauth2_provider/tests/test_auth_backends.py
oauth2_provider/tests/test_rest_framework.py
oauth2_provider/tests/urls.py
oauth2_provider/urls.py
tox.ini

`urlpatterns` should be a plain list or `django.conf.urls.url` instances.
> As stated by the [Django documentation](https://docs.djangoproject.com/en/1.9/ref/urls/), and Django 1.9 will probably remove it.
Cheers

Prepare the Django 1.9 compatibility

---

.travis.yml

Be ready for the integration of Python 3.5.
This way, we keep an eye when looking for ci builds, and we'll only need to remove the `allow_failures` key in `travis.yml`.

Add the py35-django19 env to travis but allow it to fail

---

tox.ini

I came across this syntax minutes ago, it can be easier to read and avoid annoying typo mistakes.
Cheers

Use compact syntax for tox envs

---

docs/settings.rst
oauth2_provider/oauth2_backends.py
oauth2_provider/settings.py
oauth2_provider/views/base.py
oauth2_provider/views/generic.py

Hi!
In my pull request you can find some little changes that allow to override ``server_class`` that used in ``OAuthLibMixin``. These changes are very useful for some projects which want to implement custom grant types and the best way to do this — implement own ``server_class`` based on ``oauthlib.oauth2.Server``.
Please let me know if you have any questions or I forgot to do something.
If I need to write tests according to my changes, please give me an advice what tests you want to see.
Thanks.

``server_class`` is now pluggable through Django settings

---

oauth2_provider/oauth2_validators.py
oauth2_provider/tests/test_oauth2_validators.py

`None` is a valid value for `request.encoding`, as documented: https://docs.djangoproject.com/en/1.9/ref/request-response/#django.http.HttpRequest.encoding)

Fix #340 by defaulting encoding var when request.encoding is None

---

CONTRIBUTING.rst
README.rst

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs link for their .org -> .io migration for hosted projects

---

docs/advanced_topics.rst
docs/contributing.rst
docs/tutorial/tutorial_02.rst

This is to help deal with the common questions in #196 until a final decision is made on how to restrict access to application creation/editing.
This probably needs some quick testing on a new project to ensure it works properly.

Change documentation for the Application urls

---

AUTHORS
README.rst
docs/changelog.rst
docs/rest-framework/permissions.rst
oauth2_provider/ext/rest_framework/__init__.py
oauth2_provider/ext/rest_framework/permissions.py
oauth2_provider/tests/test_rest_framework.py

fixes #265 
based on code writen by  @werthen
we use this permission to allow people to browse and use the api, based on their model perimissions, and use the rest api based on the required scopes.
This means a user can browse everything he/she has permissions to browse, 
and an app with a token can get all the information the user has permissions to, as long as it's token has the correct scope (so the users granted the right permissions)
```
permission_classes = (IsAuthenticatedOrTokenHasScope, DjangoModelPermissions)
required_scopes = ['scope1']
```

added an IsAuthenticatedOrTokenHasScope Permission

---

docs/tutorial/tutorial_01.rst

Since `django-cors-headers` has been inactive since May 2015, the documentation should suggest using `django-cors-middleware`. This is a fork of `django-cors-headers` that has been kept up to date, so it supports Django 1.10.

Suggest django-cors-middleware

---

.travis.yml
requirements/testing.txt
tox.ini

Coverage measurement has been broken since updating to pytest. See https://coveralls.io/repos/3350/builds?page=7 and https://travis-ci.org/evonove/django-oauth-toolkit/jobs/141547004, or the following screenshots
It's not completely clear WHY coverage broke, but it's simple to fix by updating to the latest pytest-cov and coverage.py

Fix coverage since pytest

---

oauth2_provider/backends.py

An OAuthLibCore object is already defined at the module level. Use that, instead of calling `get_oauthlib_core` again in the `authenticate` method.

Use the OAuthLibCore object defined at the module level.

---

docs/advanced_topics.rst
oauth2_provider/middleware.py

Hi,
Thanks again for the project and the docs! I encountered two issues while running this code on #405 and #406. I've not tested the code on older versions of Django.

Fixes #405 and #406

---

AUTHORS
README.rst
docs/changelog.rst
docs/install.rst
docs/rest-framework/getting_started.rst
docs/tutorial/tutorial_01.rst
docs/tutorial/tutorial_02.rst
docs/tutorial/tutorial_03.rst
oauth2_provider/admin.py
oauth2_provider/middleware.py
oauth2_provider/tests/settings.py
oauth2_provider/tests/test_models.py
oauth2_provider/tests/test_rest_framework.py
oauth2_provider/tests/urls.py
oauth2_provider/urls.py
tox.ini

* Added support for Django 1.10 in tox.ini
* Converted all urlpatterns to lists
* Fixed tests failing in Django 1.10

Tests now support Django 1.10

---

oauth2_provider/migrations/0004_auto_20160525_1623.py
oauth2_provider/models.py

For #382 
Add a unique constraint to the token codes to avoid `objects.get() MultipleObjectsReturned` exceptions.

Add unique constraints to models' token codes

---

README.rst
docs/settings.rst
oauth2_provider/admin.py
oauth2_provider/compat_handlers.py
oauth2_provider/forms.py
oauth2_provider/settings.py
oauth2_provider/tests/settings.py
oauth2_provider/tests/test_scopes.py
oauth2_provider/urls.py

This PR drops old Python 2.6 compatibility shims, adds better administration for the builtin models (including a crucial fix adding `access_token` to `raw_id_fields`) and splits the base and management views in `urls.py` so that either can be accessed and included separately - without breaking backwards compatibility.

Minor improvements

---

oauth2_provider/admin.py
oauth2_provider/tests/test_scopes.py
oauth2_provider/views/application.py

This pr adds on `ApplicationUpdate` view the following method:
```python
def get_form_class(self):
```
Removed field `expires` from `RefreshTokenAdmin`
Removed unused import from tests

Removed skip-authorization

---

oauth2_provider/urls.py

Fixes this warning in Django 1.10:
```
RemovedInDjango20Warning: Specifying a namespace in django.conf.urls.include() without providing an app_name is deprecated. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.
url([...], include('oauth2_provider.urls', namespace='oauth2_provider')),
```
Also, when you want to drop support for Django 1.8, it won't be necessary with this change to declare `namespace` explicitly.

Add app_name to urls.py

---

docs/advanced_topics.rst
docs/changelog.rst
docs/conf.py
docs/index.rst
docs/settings.rst
docs/templates.rst
docs/tutorial/tutorial_04.rst

**Issue**: #444 
I added ``templates.rst`` to the ``docs``.
I gave complete docs on the templates because the Views' docs are automatic and I think this way it is easier to understand how everything was implemented (simple version).
I also enabled the [intersphinx extension](http://www.sphinx-doc.org/en/1.5.1/ext/intersphinx.html) so I could map python and Django classes.
There were also some warnings on compile ("title length must match underline") and I got rid of them.
Changes in other files were only for this reason and to add references.
Feel free to change anything.

Docs on templates

---

oauth2_provider/models.py
oauth2_provider/oauth2_validators.py
oauth2_provider/tests/test_oauth2_backends.py

Hello,
Using DOT in my app, I wanted to customize my Application model to support multiple (not combined) grant flows. If I understand correctly, this is @skrivanos's request on #69 .
This PR implements a new api method on AbstractApplication  to check if the instance allows a grant type and just a few modifications on the validator so that it doesn't make assumptions on Application.authorization_grant_type and asks the application model instead.
This is transparent for the existing tests and does not decrease coverage as far as I can tell.
It doesn't seem to contradict the RFC as it doesn't forbid multiple grant flows to be allowed for one client : 
[RFC 6749 section 1.2](https://tools.ietf.org/html/rfc6749#section-1.2)
> The client receives an authorization grant, which is a
> …

Customizable application grant type

---

docs/tutorial/tutorial_02.rst

The code sample in tutorial part 2 is not working properly by simple copy-and-paste because  `include` has been removed from the default `urls.py` template since https://github.com/django/django/commit/1e82094f1b6690018228e688303295f83e1c3d9a

added missing imports in doc: Tutorial Part 2

---

oauth2_provider/validators.py
tests/test_validators.py

The empty string does no longer pass the URI validator. This does not
make existing code that relies on `blank=True' fail, it just fixes the
case where the user provides an empty string.
Signed-off-by: Rigas Papathanasopoulos <rigas@arrikto.com>

Disallow empty redirect URIs

---

docs/tutorial/tutorial_01.rst

Right position/order is essential. Thus I was curious when I couldn't find any info in the current tutorial. Checked django-cors-middleware docs and found this: https://github.com/ottoyiu/django-cors-headers#setup

added info about position of `CorsMiddleware`

---

oauth2_provider/settings.py

The settings class used `OAUTH2_PROVIDER_REFRESH_MODEL` as the setting name, while most of the code used `OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL` (which makes more sense as well), leading to conflicts.

Fix RefreshToken model setting name

---

oauth2_provider/models.py

Just a minor inconvenience but it seems unnecessary to me to parse the same
parameter value multiple times in case there are more than one permitted redirect
URIs.

Parse URI only once in AbstractApplication.redirect_uri_allowed.

---

oauth2_provider/migrations/0001_initial.py

This should fix circular migrations error like those in #525 
The changes in this PR are supported by 2 things:
- tried to remove manually the dependencies that were creating circular migratiosn dependency error which worked
- tried to rebuild django-oauth-toolkit migrations from scratch obtaining this result
Now I'm not an expert of swappable models and I don't get them totally but this solutions seems to me the right one not only because django creates the migration with only one dependency to the `user` model but because If anybody tries to subclass one of the models, I don't see how the migrations for the subclassed model can work since:
- sublcassed model migrations depend on `django-oauth-toolkit 0001`
- `django-oauth-toolkit` migration 0001 depends on `subclassed 0001`
Happy to …

Remove dependencies to models that create circular errors

---

oauth2_provider/models.py

If refresh tokens are not being used or if REFRESH_TOKEN_EXPIRE_SECONDS is not set in the settings then access tokens are never cleaned up by the `cleartokens` command.
This used to be the behaviour, but it looks like there was an un-intended indentation change in https://github.com/evonove/django-oauth-toolkit/commit/be8bcccc0adce86862c9d35ae50afc42a3a28d95

Expire AccessTokens even when REFRESH_TOKEN_EXPIRE_SECONDS is not set

---

oauth2_provider/models.py

Fix for difficult to reproduce issue of #514. 
It is a concurrency issue which I fail to reproduce in a docker/controlled environment.
This change was done for Python 3.4
In absence of reproduction capabilities we deployed this change to our production servers.
The issue hasn't come up since.

Delete Refresh token before Access Token to avoid cascade deadlock

---

oauth2_provider/models.py

From checking to see whether the refresh token is valid in `validate_refresh_token` to when it's revoked in `save_bearer_token` in `oauth2_provider/oauth2_validators.py`, multiple requests can validate the same refresh token (where it's then stored in memory) and generate multiple access tokens from it. While this is allowed by the spec and explicitly configurable via the `ROTATE_REFRESH_TOKEN`, it seems like unexpected behavior. 
To reproduce this, a fully concurrent example should be used, e.g. [the demo](https://github.com/evonove/django-oauth-toolkit-example/) with postgres and gunicorn with multiple workers and concurrent requests. This script will return multiple access tokens:
```
#!/bin/bash
curl 'http://localhost:8000/o/token/' -H 'Content-Type: application/x-www-form-urlencoded; …
```

Prevent racecondition on consuming refresh token.

---

.gitignore
oauth2_provider/views/introspect.py
tests/test_introspection_auth.py
tests/test_introspection_view.py

Replacing `ReadWriteScopedResourceView` with `ScopedProtectedResourceView`
fixes #555

Don't require write scope for introspection

---

docs/contributing.rst

The requirements files were deleted on 9th March 2017 when test requirements were moved to tox.ini. The issue of no requirements/optional.txt file was raised in issue 535, which can be closed if this PR is merged.

Remove incorrect reference to requirements from docs

---

oauth2_provider/models.py

Uses client_id as a natural key when serializing the default
Application model, so that when things like fixtures are loaded,
references are maintained even when the environment that the
fixture is being loaded to doesn't have the same primary keys as
the environment that the fixture dumped from.

Add client_id as a natural key to the default Application model

---

oauth2_provider/validators.py
tests/test_validators.py

Discovered in testing related to our project [AWX](https://github.com/ansible/awx), a django / rest framework application. In our implementation a PATCH of the sort
```json
{"redirect_uris":"https://[\"><script>alert()</script>"}
```
were causing server errors.
You could make the case that the `except` block here should just `raise` instead of this custom error. I'm indifferent, I just don't want the server error. We will monkey patch the validator until we can get this in a release.
Thanks!

Handle case broken in error handling - IPv6 URL

---

oauth2_provider/oauth2_backends.py
tests/test_authorization_code.py

Conforms to [rfc6749 section 4.1.2.1](https://tools.ietf.org/html/rfc6749#section-4.1.2.1)
> REQUIRED if a "state" parameter was present in the client
>         authorization request.  The exact value received from the
>         client.

Return state with authorization denied error

---

CHANGELOG.md
docs/rest-framework/permissions.rst
oauth2_provider/contrib/rest_framework/__init__.py
oauth2_provider/contrib/rest_framework/permissions.py
tests/test_rest_framework.py

See suggestion for a better name in #563

Rename TokenHasMethodScopeAlternative to TokenMatchesOASRequirements

---

oauth2_provider/oauth2_backends.py

If a request's body is a json list instead of a json object django-oauth-toolkit raises and exception. It breaks bulk requests for drf for example. This commit fixes it.

Ignoring requests containing list instead of dict

---

oauth2_provider/models.py
tests/test_token_revocation.py

Fixes #625
----
Lands #629 on master for cherry-picking.

Fix Refresh Token revocation when the access token does not exist

---

oauth2_provider/oauth2_validators.py
tests/test_authorization_code.py

adding the 'refresh_token' to the dictionary being returned when the refresh_token is being reused.

Fixing issue #631 - returning the refresh token of previous token

---

setup.cfg

We're going to release OAuthLib 3.0.0 soon, which contains some breaking changes.
This pinpoint is to avoid problems before we are able to address the compatibility.

Pin oauthlib to avoid breakage with 3.0.0 release.

---

oauth2_provider/oauth2_validators.py
tests/test_oauth2_validators.py

In our project we have a custom attribute on refresh token that we need to inject when creating those, for now we have the entire method save_beaer_token duplicated when we need only this bit. I thought that since there is already something similar for the AccessToken maybe the same path could be applied for RefreshToken

Add hook for creating custom refresh tokens

---

oauth2_provider/oauth2_validators.py
tests/test_authorization_code.py

Returns the new refresh token from the refresh_token endpoint instead of the old, revoked one during grace period.
Resolves #702.

Return the new refresh token during grace period (#702)

---

oauth2_provider/views/base.py
tests/test_authorization_code.py

PKCE credentials are not being captured during GET authorize requests. oauthlib should(?) return `code_challenge` and `code_challenge_method` from [grant_types.authorization_code.validate_authorization_request](https://github.com/oauthlib/oauthlib/blob/master/oauthlib/oauth2/rfc6749/grant_types/authorization_code.py#L318).
@JonathanHuot, if oauthlib does not return them, clients using oauthlib must capture them manually. Is that intended?

Fix PKCE credentials not being captured during authorize requests

---

oauth2_provider/oauth2_validators.py

Fix not supported FOR UPDATE query, fixes #714

---

oauth2_provider/contrib/rest_framework/authentication.py
tests/test_rest_framework.py

If the request doesn't have a oauth2_error property the
authenticate_header method errors. This can happen when the
oauthlib_core.verify_request method raises exceptions in authenticate.
It is useful to be able to raise AuthenticationFailed exceptions from
within a custom validate_bearer_token method which causes this.

Use getattr for oauth2_error access (#633)

---

docs/rest-framework/getting_started.rst

I had trouble getting `grant_type=password` working with the Django REST Framework example in the DOT tutorial. The answer was to set the OAuth2 backend class to `'oauth2_provider.oauth2_backends.JSONOAuthLibCore'`: https://github.com/jazzband/django-oauth-toolkit/issues/127#issuecomment-94439287
I was trying to use Angular framework with its HttpClient and I think the POST requests were sending over content with `application/json`. It would have been a better experience to see this documented in the tutorial.

getting_started.rst: add JSONOAuthLibCore as part of tutorial

---

tests/test_models.py
tests/test_token_revocation.py

Fix tests relying on non-standard behavior of old oauthlib.
Fix test fixtures that rely on outdated django.
Fix some timezone warnings too.

Fix testsuite (#748)

---

docs/tutorial/tutorial_01.rst

Fixed unpaired parentheses, At the same time, Django now provides `path` by default. Should we change the `url` to `path`?

Fixed unpaired parentheses

---

oauth2_provider/views/base.py
tests/test_authorization_code.py

This implements a check on refresh tokens for `auto` skipping of the authorization form, as described in #753.

Auto-authorize if valid refresh tokens exist

---

oauth2_provider/admin.py

Hello,
I added id field in list_display because, when create a application register without name, this item stay without link to click to change it.

Add id in list_display on AplicationAdmin.

---

oauth2_provider/models.py
oauth2_provider/oauth2_validators.py

Change ugettext_lazy by gettext_lazy to remove Django 3.0 DeprecationWarning
- Log Sample:
```shell
.../lib/python3.7/site-packages/oauth2_provider/models.py:41: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
(CLIENT_CONFIDENTIAL, _("Confidential")),
.../lib/python3.7/site-packages/oauth2_provider/models.py:42: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
(CLIENT_PUBLIC, _("Public")),
.../lib/python3.7/site-packages/oauth2_provider/models.py:50: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
(GRANT_AUTHORIZATION_CODE, …
```

Remove Django 3.0 DeprecationWarning

---

oauth2_provider/admin.py

This PR adds `source_refresh_token` to `raw_id_fields` within `AccessTokenAdmin` to significantly reduce the time it takes to load the detail view of any access token inside the admin site when there are a large number of refresh tokens.
This should resolve #777.

Reduce detail page load time in admin site for access tokens

---

docs/install.rst
docs/tutorial/tutorial_01.rst
docs/tutorial/tutorial_02.rst
docs/tutorial/tutorial_03.rst

* Updated install.rst, tutorial_01, tutorial_02, and tutorial_03 to use 'path' instead of 'url' for urlpatterns.

Updated 'url' with 'path' in documentation

---

.github/pull_request_template.md
AUTHORS

Fixes #
Now that we have a single changelog (#791), there is no need to update docs/changelog.rst.

Fix template one changelog

---

.travis.yml
tox.ini

Fixes #
Restores commented-out tox tests.
Converts travis to explicit matrix to enable allowed failing tests against django master.

Restore djangomaster tests

---

.github/pull_request_template.md
CHANGELOG.md

Fixes #
Adds descriptions of previously undocumented merged PRs (based on reading the
commit history, PRs, issues). Switches over to [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) style.

document undocumented PRs 1.2.0 -> 1.3.0

---

README.rst
docs/index.rst

Fixes #
Documentation update: Make it clear that oauthlib>=3.0 is required since we were previously pinned <3.0.
See #785

sync up requirements documentation

---

oauth2_provider/management/commands/createapplication.py
oauth2_provider/models.py
oauth2_provider/oauth2_validators.py
oauth2_provider/settings.py
oauth2_provider/validators.py
oauth2_provider/views/base.py
tests/models.py
tests/settings.py
tests/test_application_views.py
tests/test_authorization_code.py
tests/test_commands.py
tests/test_rest_framework.py
tests/test_token_revocation.py
tox.ini

Fixes #796 
Restore flake8 tests that were disabled with `--exit-zero` and commenting out `flake8-quotes`
Required a few minor syntax changes a handful of files.

Restore disabled flake8 tests

---

docs/contributing.rst

Fixes #
Update the contribution guidelines to remove reference to former google group and add more details on what's expected in a PR, such as this checklist:

improve contributing guidelines

---

setup.cfg
tox.ini

Fixes #804
- add long_description (README.rst) so it shows up nicely on [pypi](https://pypi.org/project/django-oauth-toolkit/1.3.0/)
- add 'tox -e install' as a reminder of how to 'twine upload' pending fixing github webhooks.

pypi improvements

---

CHANGELOG.md
oauth2_provider/oauth2_validators.py

Fixes #808 
Reverts jazzband/django-oauth-toolkit#643

Revert "Fix issue 636, pass request object to authenticate function."

---

oauth2_provider/oauth2_validators.py

When I scale my back-end to have multiple django instances running to help with growing server demand I sometime receive the following stacktrace error:
```
ERROR [django.request] [log] [2020-03-10 08:46:47,169] Internal Server Error: /api/oauth2/token/
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 164, in __get__
rel_obj = self.field.get_cached_value(instance)
File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
return instance._state.fields_cache[cache_name]
KeyError: 'access_token'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```

Fix fetching old access_token from refresh_token

---

CHANGELOG.md
docs/rest-framework/getting_started.rst

Reverts jazzband/django-oauth-toolkit#734 per #807

Revert "getting_started.rst: add JSONOAuthLibCore as part of tutorial"

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/pull_request_template.md

- Add instructions as template comments.
- Fix misunderstanding of how labels work.

Improve PR and Issue templates.

---

CHANGELOG.md
setup.cfg

Fixes #819 
No code changes here but a [new version is required by pypi](https://pypi.org/help/#file-name-reuse) due to inadvertently packaging an extra migration that was laying around from a dev branch.

bump the version to 1.3.2 to allow fixing an incorrect twine upload of 1.3.1

---

docs/tutorial/tutorial_01.rst
docs/tutorial/tutorial_03.rst

Remove Django 1.x code example from tutorial, because oauth2_provider only supports Django 2.x and 3.x.
- [x ] PR only contains one change (considered splitting up PR)
- [x ] documentation updated

remove django 1.10 example from tutorial

---

README.rst
docs/index.rst
docs/requirements.txt
oauth2_provider/views/base.py
setup.cfg
tox.ini

OAuthLib landed PKCE support in 3.1.0 version via https://github.com/oauthlib/oauthlib/pull/671. Therefore there is no need for work-around in django-oauth-toolkit.
Docs where failing due to m2r lacks compatibility with sphinx 3.x, so had to specify sphinx version to be lower than 3.
Maybe we need a new release with this change.

pkce in oauthlib 3.1.0

---

oauth2_provider/oauth2_validators.py

I'm subclassing OAuth2Validator to customize authorization code generation, and splitting authorization code creation into _create_authorization_code like _create_access_token, _create_refresh_token would make it easy. Otherwise, I would copy paste same code from save_authorization_code to customize it.

split authorization code creation into OAuth2Validator._create_authorization_code 

---

docs/install.rst

Changes install documentation to include missing imports and split `path()` vs re_path()` solutions.

Change install documentation to include missing imports

---

AUTHORS
CHANGELOG.md
oauth2_provider/oauth2_validators.py
tests/test_oauth2_validators.py

By providing the status code and its reason to logger, the error message would be more explicit for debugger whenever there is an issue related to resource token or other errors.
Fixes #847 
Added a checker to log an exception when the response from authentication server is not successful. With such change, the real issue with the response would not be changed to a JSONDecoderError which would be a distraction for debugging.

Fix #847 Log an exception when response status is not OK

---

tests/test_introspection_auth.py
tests/test_rest_framework.py

url() is deprecated in Django 3.1 change to path() and re_path()

Changed url() to path() and re_path()

---

oauth2_provider/signals.py

For documentation only -- left in code as a comment
```
RemovedInDjango40Warning: The providing_args argument is deprecated.
As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docst
ring.
app_authorized = Signal(providing_args=["request", "token"])
```

Passing `providing_args` into `Signal` is deprecated

---

AUTHORS
tests/test_auth_backends.py

passing get_response into middleware is deprecated in Django 3.1. This pull request creates a fake request object to pass into the middleware.

Passing None into middleware is deprecated

---

oauth2_provider/backends.py
oauth2_provider/generators.py
oauth2_provider/oauth2_backends.py
oauth2_provider/scopes.py
oauth2_provider/settings.py
oauth2_provider/views/mixins.py
tests/test_mixins.py

A small tidy up -- `object` is no longer required.

Removed inheritance from `object`

---

tests/urls.py

URL() is deprecated in Django 3.1 and path() is available in all supported versions of Django.

Updated url() to path()

---

CHANGELOG.md

Update changelog for 1.3.3 release

---

docs/contributing.rst

Improve documentation for contributors and project leads.

improve contributing docs

---

AUTHORS
oauth2_provider/views/base.py
tests/test_authorization_code.py

Hi :wave: 
first of all thanks for developing and maintaining a great project!
Pass `code_challenge` and `code_challenge_method` from query string to `AuthorizationView` form in `get()`.
Without this, it was impossible to use authorization code grant flow with `GET`, because `code_challenge` and `code_challenge_method` data were never passed to form, so they weren't in `form.cleaned_data`, which causes creating `Grant` with always empty `code_challenge` and `code_challenge_method`.
This issue was quite hard bug to discover because there are already few tests for authorization code flow pkce, however, they weren't checking form rendering in `GET` request, but only `response.status_code`, I have added asserts for these 2 values, please look at the changes in …

pass PKCE fields to AuthorizationView form

---

docs/getting_started.rst
docs/index.rst

Fixes #
Fixed grammar and spelling mistakes

Fixed some grammar and spelling mistakes in the docs.

---

.travis.yml
CHANGELOG.md
setup.cfg
tox.ini

Adds Python 3.9 to test matrix. Currently, released versions of Django don't officially support Python 3.9 but let's test against the 'master' branch for now.

Added Python 3.9 to test matrix for djangomaster

---

docs/Makefile
docs/conf.py
docs/contributing.rst
tox.ini

Add a new tox target, `livedocs`, that uses `sphinx-autobuild` to monitor the docs and auto rebuild the HTML docs when they change.
It also starts a webserver on 127.0.0.1:8000 using `livereload` to serve the docs, which will automatically reload the pages in your browser as they are changed.
Add docs on updating the docs.
Add `sphinx-rtd-theme` so that the docs generated in development match the style that they are displayed in on readthedocs.
This shouldn't affect test run time; the `livedocs` tox target is only run when explicitly asked for, and packages are only installed when using `livedocs`

Add live docs rebuilding using sphinx-autobuild

---

docs/settings.rst

This PR adds to the documentation details of the access token expires and a stronger suggestion to expire refresh tokens.

Update docs to about default ACCESS_TOKEN_EXPIRE_SECONDS

---

AUTHORS
CHANGELOG.md
docs/contributing.rst
oauth2_provider/locale/pt/LC_MESSAGES/django.po
oauth2_provider/templates/oauth2_provider/application_confirm_delete.html
oauth2_provider/templates/oauth2_provider/application_form.html
oauth2_provider/templates/oauth2_provider/application_list.html
oauth2_provider/templates/oauth2_provider/authorize.html
oauth2_provider/templates/oauth2_provider/authorized-token-delete.html
oauth2_provider/templates/oauth2_provider/authorized-tokens.html

Fixes #690, #919
Due to some confusion around ability to merge #690 this PR is my 2nd attempt. I've taken #690 and made some changes:
- Added @srtab's name to AUTHORS
- Updated the CHANGELOG
- Removed unnecessary header comments from LC_MESSAGES/django.po
- Updated docs/contributing.rst to describe how to add additional translations.
I don't know if there's a need for unit tests to confirm the translations are working as expected.

3rd try at getting pt-PT PR #690 to merge

---

AUTHORS
CHANGELOG.md
setup.cfg

prepare for 1.4.0 release

---

AUTHORS
CHANGELOG.md
oauth2_provider/middleware.py
tests/test_auth_backends.py
tox.ini

Remove MiddlewareMixin use, and convert to new style Django middleware.

remove MiddlewareMixin use

---

oauth2_provider/middleware.py
tox.ini

Run lint in Github Actions to avoid PRs being merged that have accidentally included linting violations.
Fix a file that has a linting violation.

Run "lint" in Github Actions

---

docs/tutorial/tutorial_02.rst

Fix wrong import from `url` (unused in example) to `path`.
Fixes #
Just a quick fix.

Fix wrong import

---

AUTHORS
docs/models.rst
docs/templates.rst
oauth2_provider/locale/pt/LC_MESSAGES/django.po
oauth2_provider/templates/oauth2_provider/authorize.html

The existing message to users was 'Application requires following permissions' which sounds
like bad english to me. I've changed them to 'Application requires the following permissions'.

Fix weird grammar in messages on authorize screen

---

.github/workflows/test.yml
AUTHORS
CHANGELOG.md

Previously, every pull request was running actions twice, since two signals were fired - push commit in the PR and new PR itself.
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#webhook-events

GitHub Actions: smart run strategy

---

.github/workflows/test.yml
AUTHORS

Reverts jazzband/django-oauth-toolkit#937
See the discussion in https://github.com/jazzband/django-oauth-toolkit/pull/937

Revert "GitHub Actions: smart run strategy"

---

.github/workflows/test.yml
AUTHORS
CHANGELOG.md
README.rst
docs/index.rst
pyproject.toml
setup.cfg
tox.ini

Python 3.5 did reach end-of-life in September 2020:
https://www.python.org/downloads/release/python-3510/
We can safely remove it from CI to reduce test running time.

Drop retired Python 3.5

---

CHANGELOG.md
oauth2_provider/models.py
setup.cfg

Fixes: #923 
A few minor changes. See [CHANGELOG.md](CHANGELOG.md)

1.4.1 release

---

AUTHORS
CHANGELOG.md
setup.cfg

- Adds OpenID Connect 1.0 (OIDC).
- Added all co-authors of the OIDC PR to AUTHORS and sorted alphabetically.

Release 1.5.0

---

AUTHORS
CHANGELOG.md
docs/settings.rst
oauth2_provider/oauth2_validators.py
tests/test_introspection_auth.py

Fixes #
Fixes #524. Restrict usage of timezone aware expire dates to Django projects with USE_TZ set to True.

Fix #524 - Restrict usage of timezone aware expire dates to Django projects with USE_TZ set to True

---

AUTHORS
CHANGELOG.md
oauth2_provider/oauth2_validators.py

Fixes #712
Fixes #636
Fixes #808
The function django.contrib.auth.authenticate() has an optional first `request` argument. Some backends, such as django-axes (i.e. the subject of #712) and others (i.e. the subject of #636) *require* this argument to be present. This change provides this argument.
Additionally, this change is based on the patch in #712, and constructs a Django HttpRequest object from the DOT request object in order to provide API compatibility. This avoid the issue that caused the original fix for #636 to be reverted, and also addresses #808.

Provide django.contrib.auth.authenticate() with a request for compatibiity with more backends. 

---

AUTHORS
CHANGELOG.md
oauth2_provider/views/oidc.py
tests/presets.py
tests/test_oidc_views.py

According to the `django-oauth-toolkit` documentation for [OIDC_ISS_ENDPOINT](https://django-oauth-toolkit.readthedocs.io/en/latest/settings.html#oidc-iss-endpoint) this settings variable should enable discovery at `OIDC_ISS_ENDPOINT` + `/.well-known/openid-configuration/`. This behaviour is backed by the OIDC [specs](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig).
But if you use the variable as described you'll end up with the correct URL for the `issuer` value but incorrect URL's for the values of `authorization_endpoint`, `token_endpoint`, `userinfo_endpoint`, and `jwks_uri` in the json response when calling `/.well-known/openid-configuration/`. 
So if the `OIDC_ISS_ENDPOINT` is `http://localhost:8001/some-initial-path/o` the `issuer` will be …

Fix double oauth2_provider mountpoint in oidc view

---

AUTHORS
CHANGELOG.md
docs/settings.rst
oauth2_provider/models.py
tests/test_oauth2_backends.py

Allow loopback redirect URIs with ports using http scheme and localhost addresses (127.0.0.1 or ::1),
as described in RFC8252 (section 7.3).

Allow loopback redirect URIs using ports as described in RFC8252

---

AUTHORS
CHANGELOG.md
README.rst
setup.cfg
tox.ini

Fixes #
- Remove Django 3.0 support
- Add Django 3.2 support
- Add Python and Django supported versions badges to README

Update django support

---

AUTHORS
CHANGELOG.md
oauth2_provider/models.py
oauth2_provider/views/introspect.py

Fixes #987 
Changes any valid `HttpResponse(json.dumps(), etc...` to `django.http.JsonResponse`

Change remaining HttpResponse to JsonResponse

---

AUTHORS
docs/tutorial/tutorial_01.rst

References #411 
Change docs to use django-cors-headers instead of django-cors-middleware which has been archived as a repo. Django-cors-headers resumed maintenance.
Besides installation, INSTALLED_APPS and the rest stays the same (since django-cors-middleware was a fork).

Use django-cors-headers in docs

---

AUTHORS
oauth2_provider/admin.py

This is needed to avoid 2 extra DB queries per each line in the list view, so that is usually +200 unnecessary queries.

Optimize DB access in AccessTokenAdmin

---

docs/settings.rst

Add that REFRESH_TOKEN_EXPIRE_SECONDS can be an `Int` or `datetime.timedelta` to settings.rst.

Update settings.rst with text 

---

oauth2_provider/models.py

Add a space to multi-line string so the words "authorization_code" and "or" are properly separated

Add missing space in assertion error

---

AUTHORS
docs/tutorial/tutorial_01.rst

In a newly created Django project (version 3.2.1) the `include` function is not imported.

Add missing import

---

docs/tutorial/tutorial_03.rst

`AUTHENTICATION_BACKENDS` and `MIDDLEWARE` should be arrays, not tuples. Using tuples seems to work, but everything else in the settings.py file is an array.
Fixes #

Update tutorial_03.rst to use arrays instead of tuples in the settings.py file

---

AUTHORS
oauth2_provider/__init__.py
setup.cfg

Replaced pkg_resources usage with importlib.metadata
Setuptools discourages use of pkg_resources in favour of importlib.resources and importlib.metadata. (Ref: [pkg_resources](https://setuptools.pypa.io/en/latest/pkg_resources.html))

Replaced pkg_resources usage with importlib.metadata

---

oauth2_provider/__init__.py
setup.cfg

Moved version info from setup.cfg into package.
It is better to make setup.cfg infer version info from the package instead of vice versa.
Previous method only works where the package is "installed".
It doesn't work if we were to use this as a git submodule or frozen environments like nuitka.

Moved version info from setup.cfg into package

---

.github/workflows/test.yml
AUTHORS
docs/requirements.txt
oauth2_provider/__init__.py
tox.ini

Fixes Django Deprecation Warning
`/usr/local/lib/python3.9/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'oauth2_provider' defines default_app_config = 'oauth2_provider.apps.DOTConfig'. Django now detects this configuration automatically. You can remove default_app_config.`
- N/A unit-test added
- N/A documentation updated
- N/A `CHANGELOG.md` updated (only for user relevant changes)
Confirmed that tox passed locally

Removes default_app_config for Django Deprecation Warning

---

AUTHORS
CHANGELOG.md
oauth2_provider/admin.py

Fixes:
* long loading times of admin edit pages when many User/Token models
I defined `search_fields`, `list_filters` and `raw_id_fields` for easier management of the tokens in admin.
Not sure what to test in this.
Also I think, this doesn't need any documentation, it is pretty self-explanatory to users.

upgrades to admin: search_fields, list_filters and raw_id_field

---

.github/workflows/test.yml
CHANGELOG.md
README.rst
docs/index.rst
setup.cfg
tox.ini

Fixes #1037 
Add support for Dj40, drop Py36 and Dj31
Dj31 and Py36 will be EOL end of this December of 2021. I do not want to hold back any PRs that need to support old versions of stuff, thus I have dropped those two.

Add support for Dj40, drop Py36 and Dj31

---

.github/workflows/test.yml
tox.ini

In https://github.com/jazzband/django-oauth-toolkit/commit/345122881424897a2907312db52fafad9bbaa5f1, I added a tox dependency for django in the wrong place.
Very minor change, just adding it to tox.ini instead.

Move tox django dependency to proper place

---

.readthedocs.yml
docs/requirements.txt

Fix #1049.
This will fix RTD installing conflicting Django versions.

Remove Django pinning in doc requirements.

---

docs/contributing.rst

Improve contributing documentation to ask that a reviewer gets assigned from the project team.

Update contribution guidelines to request PR review by project team.

---

CHANGELOG.md
README.rst

Fixes #1051 
Clarifies why Django 4.0.0 specifically isn't supported but 4.0.1 will be supported.
Updates README (for upfront dev purposes) and docs (updated CHANGELOG since that goes into our RTD for SEO/Google and RTD search engine purposes).

Clarify why Django 4.0.0 isn't supported

---

CHANGELOG.md
README.rst
oauth2_provider/__init__.py

1.6.1 release

---

AUTHORS

Fixes #
Workaround problem where the precommit merge hook breaks on the 7-character doulbe-underline for AUTHORS by having a false-positive broken commit error. 
It pains me to do this but I'd rather catch actual merge conflicts than exclude checking this file.

Replace RST header underline with one that pre-commit check-merge won't break on.

---

AUTHORS
CHANGELOG.md
oauth2_provider/locale/pt_BR/LC_MESSAGES/django.po

Add pt-BR locale translation (brazilian portuguese) for the django-oauth-toolkit application.

add pt_BR locale translation

---

docs/contributing.rst
tox.ini

Fixes #
Update contributing docs and tox.ini to match how releases are now done.

Improve documentation of the release process.

---

AUTHORS
CHANGELOG.md
oauth2_provider/views/introspect.py
tests/test_introspection_view.py

Compare with https://datatracker.ietf.org/doc/html/rfc7662
Fixes #

Not existing tokens should return 200 within introspection (not 403)

---

AUTHORS
CHANGELOG.md
docs/oidc.rst
oauth2_provider/oauth2_validators.py
oauth2_provider/views/oidc.py
tests/test_oidc_views.py

Fixes #1066 
PR #967 should never have been merged as it changes the signature of a published API.

#1066: Revert #967 which incorrectly breaks API.

---

CHANGELOG.md
oauth2_provider/migrations/0005_auto_20211222_2352.py

I wanted to double check that 4.0.1 wouldn't create a new migration. Turns out, I missed a comment from the PR that mentions how a migration would still be created. The reason is because of the related_name using the placeholder itself now rather than using "oauth2_provider".
Fortunately, this migration isn't as drastic as the `auth.User` one which would have deleted data... Let me know if I'm missing anything else.

Add migration due to noop FK from Django 4.0

---

oauth2_provider/admin.py

…
Fixes #1083 
* Fixes #1083
* Adds search fields to the remaining admin classes

fix #1083 ('token' not valid search field), add search fields to all remaining admin classes

---

CHANGELOG.md
oauth2_provider/__init__.py

Update stable/1.6 branch into master.

Add 1.6.3 bugfix into master.

---

oauth2_provider/management/commands/cleartokens.py
tests/test_models.py

Fixes #1065
* Flags no coverage for cleartoken management command since the test is in test_models.
* Expand coverage of the clear_expired tests.

Enhance clear_expired tests.

---

AUTHORS
CHANGELOG.md
docs/management_commands.rst
oauth2_provider/tasks.py

This adds a Celery task to clean expired tokens. It can be used to schedule token cleanup in the background, for applications using Celery and Celery beat.
The `tasks` module is autodiscovered in projects that use Celery, and should not be loaded in other projects, so this does not introduce any new dependency,

Add Celery task for cleantokens

---

docs/settings.rst
oauth2_provider/settings.py

Fixes #1087
Sets the default value time to pause between iterations of batch clear_expired tokens to zero.

Issue 1087/default batch interval

---

AUTHORS
CHANGELOG.md
docs/oidc.rst
oauth2_provider/oauth2_validators.py
oauth2_provider/views/oidc.py
tests/test_oidc_views.py

** Please do not squash the commits. I analyse my FOSS contributions automatically and really want to track commits I made.**
This is a second shot at #967, after the drama with #1066 and #1068 ;).
It re-introduces the same change @AndreaGreco proposed, and in fact, it supports their exact desired API for `get_additional_claims`. In addition, it supports the "traditional" API for `get_additional_claims` getting passed a request directly and producing data directly.
I chose to support both due to the rationale explained in the docs in this PR.

Add claims_supported to discovery info, without breaking the API

---

CHANGELOG.md
oauth2_provider/views/oidc.py
tests/test_oidc_views.py

Fixes #
Adds "scopes_supported" to openid-configuration metadata response.

OIDC: Add "scopes_supported" to openid-configuration.

---

AUTHORS
setup.cfg

Simply excluding `tests` is not enough to prevent subpackages from also being excluded. If a wildcard is provided to `find_packages(exclude=`, it will only match a single hierarchy level.
Without this, a directory `site-packages/tests/migrations` gets created upon package install.

Prevent the tests/migrations directory from getting packaged

---

AUTHORS
docs/oidc.rst

`inport os.environ` is incorrect since environ is not a module,  instead we just need to do `import os` and use `os.environ`

Fix broken import in doc

---

CHANGELOG.md
docs/management_commands.rst
oauth2_provider/tasks.py

Fixes #1114 
Fixes #1123
#1070 was apparently not tested (and was not supplied with a test case). It could never have worked and also has since been flagged as conflicting with Huey's auto-discovery which also uses `tasks.py`.
A future PR _might_ come which will document how to configure a Celery `clear_tokens` task.

Revert 1070 (Celery tasks.py)

---

CHANGELOG.md
docs/management_commands.rst
oauth2_provider/__init__.py
oauth2_provider/tasks.py

Merges fixes in #1126 into the stable/1.7 branch.

Merge hotfix 1.7.1

---

tox.ini

Pin Jinja2 version to fix breaking sphinx execution.

Pin Jinja2 version per https://github.com/sphinx-doc/sphinx/issues/10291

---

oauth2_provider/__init__.py

I update the changes made to master into stable/1.7 but forgot to update the version in master.
This fixes that.

Missed updating master branch version to 1.7.1

---

AUTHORS
CHANGELOG.md
docs/management_commands.rst
oauth2_provider/management/commands/createapplication.py
tests/test_commands.py

Fixes #
N/A
Greetings!
This pull request updates the createapplication management command.
* The `--algorighm` parameter is added which allows specification of `""`, `"RS256"`, or `"HS256"`
* The `--skip-authorization` help text is fixed
* It was previously incorrectly described as `"The ID of the new application"`
* It is now described as `"If set, completely bypass the authorization form, even on the first use of the application"`
Notes:
* Documentation not updated because:
* the command does not appear to be included in documentation
* the command is self-documented (arguments and help strings displayed on invocation)
I hope you find this change useful!
\- Daniel.

Update `createapplication` command

---

docs/resource_server.rst

Corrects missing links to glossary and documentation:
- Authentication Server -> Authorization Server
- tutorial doc reference

Corrections to resource server documentation

---

CHANGELOG.md
oauth2_provider/__init__.py

Release 2.0.0

---

AUTHORS
CHANGELOG.md
docs/oidc.rst
oauth2_provider/views/base.py
tests/test_authorization_code.py

Hi team, thanks for the great library!
Adds support for `prompt=login` to comply with https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

Support prompt login

---

docs/tutorial/tutorial_03.rst

Typo correction (Dango --> Django)

Corrected typo

---

docs/getting_started.rst

Fixed a typo in documentation which was causing the viewer to misbehave for .rst file.

fixed typo which caused incorrect display of code block

---

tests/test_models.py

Fixes #1165
Removes problematic bulk_create from test_models.
- Fixes erroneous test that was missing cases under dj32 because pk was being returned as null and not noticed.
- Resolves errors running under dj40 (albeit only locally on MacOS -- for which I still don't understand why).
- Updates tests to confirm that test objects were in fact created as expected.

Remove bulk_create due to changed behavior between dj32 and dj40.

---

CHANGELOG.md
oauth2_provider/__init__.py
setup.cfg

Fixes #
Release 2.1.0
It's past due time to get this out there for the hashed migrations fix especially.

Release 2.1.0

---

AUTHORS
CHANGELOG.md
docs/getting_started.rst

Fixes #1178
The getting started tutorial excludes the 'code_verifier' when fetching the access token. This is causing confusion, example https://github.com/jazzband/django-oauth-toolkit/issues/1178

Add 'code_verifier' parameter to token request

---

docs/contributing.rst

The tox environment to run flake8 changed in https://github.com/jazzband/django-oauth-toolkit/commit/6af081c8053dc9712cb4822f5c876d18269b7851.

Fix tox env used for flake8 in contributing docs

---

AUTHORS
CHANGELOG.md
setup.cfg
tox.ini

Fixes #1202
Remove upper version bound, as I recommended on the ticket.

Test Django 4.1 and remove upper version bound

---

AUTHORS
CHANGELOG.md
docs/getting_started.rst

Fixes #1207
`code_challenge_method=S256` in authorize call added in getting_started documentation

Hotfix- CODE_CHALLENGE instead of CODE_VERIFIER in docs

---

AUTHORS
CHANGELOG.md
oauth2_provider/oauth2_backends.py
tests/test_oauth2_backends.py

handle oauthlib errors on create token and revoke token requests

---

CHANGELOG.md
docs/settings.rst

Fixes #1211 
Fix confusing documentation about `AUTHORIZATION_CODE_EXPIRE_SECONDS`.
Matching `Default` `ACCESS_TOKEN_EXPIRE_SECONDS` like in the other settings in docs.

Hotfix- authorization_code_expire_seconds docs clarified

---

tox.ini

Fixes #1226 
flake8 6.0.0 made a breaking change that flake8-quotes has not caught up to yet. See https://github.com/zheller/flake8-quotes/issues/110
temporarily pin the version.

Pin flake8 version until flake8-quotes catches up.

---

tox.ini

Replaces deprecated tox.ini `whitelist_externals` with `allowlist_externals`.  This is breaking any new PR as of the tox version upgrade.

tox whitelist_externals deprecated and replaced with allowlist_externals

---

oauth2_provider/models.py
oauth2_provider/oauth2_validators.py
oauth2_provider/views/oidc.py
tests/test_oauth2_validators.py

Apply [version 23.1.0 of Black](https://black.readthedocs.io/en/stable/change_log.html#id1) which comes with some changes to the codestyle.
- n/a unit-test added
- n/a documentation updated
- n/a `CHANGELOG.md` updated (only for user relevant changes)

Format with new Black version 23.1.0

---

docs/settings.rst

Fixes [1240](https://github.com/jazzband/django-oauth-toolkit/issues/1240)
Removed 'known bug' from documentation due to it is not happening. 
The known bug states that when the `ROTATE_REFRESH_TOKEN` setting is set to `False`, was causing that both refresh token and access token get revoked
For testing that this is working correctly I set the ROTATE_REFRESH_TOKEN to False in the `OAUTH2_PROVIDER` setting in `settings.py` file and then:
1. Created a password based application
2. Requested an access token using `password` as `grant_type`
3. Used the returned refresh token to run a new request but this time with `refresh_token` as `grant_type`
Tested that:
- The response included the **same** refresh_token in the response, and updated the access_token with a new value. 
- Revoked the old …

Fix documentation regarding rotate_refresh_token setting

---

AUTHORS
docs/tutorial/tutorial_01.rst

Fixes #875 
Rewrite documentation to use postman and not the defunct Heroku service.
- [N/A] `CHANGELOG.md` updated (only for user relevant changes)

Doc: Replace heroku service with postman in tutorial part 1

---

.github/workflows/test.yml
tox.ini

Adds an additional job matrix that includes all the Django versions this package supports and excludes certain combinations of Python and Django from running. Also removes the `max-parallel` restriction for parallel CI jobs.
This should dramatically speed up CI tests, cutting almost 20 minutes from the total runtime.
Note: I have another open PR (#1218) that adds Python 3.11 to CI and tox. Either this PR or that one will need to be rebased once either one is accepted and merged.
**~25 minutes**
**~8 minutes**

Parallelize CI workflow by adding Django versions to job matrix

---

.github/workflows/test.yml
README.rst
setup.cfg
tests/settings.py
tox.ini

Test on Django 4.2

---

AUTHORS
docs/tutorial/tutorial_03.rst

Fixes #684 
There's changes in [SessionAuthenticationMiddleware](https://docs.djangoproject.com/en/4.2/releases/1.8/#using-authenticationmiddleware-without-sessionauthenticationmiddleware). I'm just slightly modified docs.

Actualize docs about AuthenticationMiddleware

---

AUTHORS
CHANGELOG.md
oauth2_provider/views/oidc.py
tests/test_oidc_views.py

Fixes #1269
Fix RP initiated logout when there's no django session available.

Fix RP-initiated Logout with expired Django session

---

tests/conftest.py
tests/test_oidc_views.py

The fixture was named `loggend_in_client` instead of `logged_in_client`

Fix typo in pytest fixture name

---

tox.ini

This reverts commit 8f8b294130fddfe177d9144d1b2dfc60f0c8c9af.
Unpins the flake8 version now that flake8-quotes has caught up to the breaking change.

Revert "Pin flake8 version until flake8-quotes catches up."

---

AUTHORS
CHANGELOG.md
oauth2_provider/__init__.py

Release 2.3.0

---

CHANGELOG.md
oauth2_provider/views/oidc.py
tests/test_oidc_views.py

Fixes #1280
Don't crash when we only have a AnonymousUser to logout (no id_token_hint or existing session),

Fix RP Initiated Logout when no user is found

---

.pre-commit-config.yaml
AUTHORS
CHANGELOG.md
docs/tutorial/tutorial_03.rst
oauth2_provider/middleware.py
tests/test_auth_backends.py

Fixes #1185
Add the Token object to the request in the middleware. This makes it easy to access the Application object in views.

Issue 1185 add token to request

---

README.rst
docs/getting_started.rst
docs/index.rst
docs/resource_server.rst
docs/rfc.py
docs/tutorial/tutorial_04.rst
oauth2_provider/generators.py
oauth2_provider/oauth2_validators.py
oauth2_provider/views/introspect.py
tests/test_authorization_code.py
tests/test_hybrid.py
tests/test_implicit.py
tests/test_oauth2_validators.py

Fixes #1313
This updates RFC references that pointed at now-deprecated `tools.ietf.org` to use `rfc-editor.org` instead. Several links were updated from http to https. A reference in `oauth2_validators.py` was still referring to an old revision of the pre-RFC draft, so I've updated that to the corresponding section of the published RFC (the text in that section looked unchanged at a glance).

Update RFC URLs to modern location

---

docs/advanced_topics.rst
oauth2_provider/views/oidc.py
tests/test_oidc_views.py

Following this comment : https://github.com/jazzband/django-oauth-toolkit/pull/1270#issuecomment-1556033128 I tried to refactor the view.
- removing post_logout_redirect_uri from validate_logout_request outputs
- adding a must_prompt method in the view (which would additionally allow anybody to easily override it)
@dopry I didn't have a revelation on how to completely clean those multiple variables.
The fact that we need to call `validate_logout_request()` from both `form_valid()` and `'get()` does not help.

Refactor RPInitiatedLogoutView

---

AUTHORS
CHANGELOG.md
oauth2_provider/migrations/0006_alter_application_client_secret.py

Fixes #
Added reverse action for migration 0006
Without reverse action it's impossible to revert applied migration

Issue 1295. Added revert action for migration

---

docs/rest-framework/getting_started.rst

The Insert user example is the same as the last example saying it will present a permission error. People reading this will get an error trying what is shown as a positive result example.
Fixes #

Updated Insert user example with scope.

---

tests/test_oidc_views.py

I've fixed the coverage issue from #1274.
The two lines from the deprecated `validate_logout_request()` function were not tested in the unit test, only in larger tests that no longer call this function (as the code now uses the view method instead)

Improve coverage following #1274

---

oauth2_provider/migrations/0007_application_post_logout_redirect_uris.py
oauth2_provider/models.py

Fixes #1309
Adding a default value to post_logout_redirect_uris model and migration

Add default value for Application.post_logout_redirect_uris

---

AUTHORS
CHANGELOG.md
docs/getting_started.rst

Fixes #1322
This resolves an issue with the instructions for generating a code challenge and code verifier. Following the instructions resulted in an error rather than getting the correct token details.

Resolved documentation issue with Code Verifier and Code Challenge

---

docs/requirements.txt

see: https://blog.readthedocs.com/defaulting-latest-build-tools/
Fixes #1330
add missing requirements
- [N/A] unit-test added 
- [N/A] documentation updated 
- [N/A] `CHANGELOG.md` updated (only for user relevant changes)

fix: rtd build missing dependencies

---

AUTHORS
oauth2_provider/oauth2_validators.py
tests/test_oauth2_validators.py

#1311 allowed the use of unhashed client secrets, but if a secret is unhashed it does not work if the client includes it's client_id and client_secret in the request body, instead of using basic auth- only hashed secrets work in that case.
This PR allows hashed or unhashed secrets in _authenticate_request_body too, and adds a test for this case.
I think this is small enough that it can really just be considered part of 1311 in terms of documentation and changelog- but if I'm wrong please let me know and I can come back.

Fix unhashed secret to work with request body authentication.

---

AUTHORS

- L with stroke should be treated as L
- pySilver out of place, do we need a real name here for posterity?
fix sort in AUTHORS file
- [N/A] documentation updated
- [N/A] `CHANGELOG.md` updated (only for user relevant changes)

fix: AUTHORS alpha sort

---

tests/app/idp/idp/apps.py
tests/app/idp/idp/settings.py

Use updated CORS support for /token in tests/app/idp to use the work from #1229. The corsheaders app is still used for the userinfo endpoint.  
I also updated the CHANGELOG.md with the Add from #1229 since I made a mess of that merge.
- [N/A] documentation updated

feat: update test idp to use new cors

---

CHANGELOG.md
oauth2_provider/models.py
oauth2_provider/oauth2_validators.py
oauth2_provider/validators.py
tests/test_models.py
tests/test_validators.py

Fixes #1336
Add scheme validation with detailed error messaged to AllowedURIValidator, and use in place of RedirectURIValidator
- add support for custom scheme validation error messages.
- deprecate RedirectURIValidator 
- deprecate WildcardSet

refactor: just one URI validator

---

AUTHORS
CHANGELOG.md
oauth2_provider/oauth2_validators.py
tests/test_authorization_code.py

Fixes https://github.com/jazzband/django-oauth-toolkit/issues/1318
We are now try / except when attempting to find a vali token to avoid a 500 `oauth2_provider.models.AccessToken.DoesNotExist: AccessToken matching query does not exist`

Fix access token 500

---

.github/workflows/test.yml
CHANGELOG.md
README.rst
oauth2_provider/__init__.py
setup.cfg
tests/test_application_views.py
tox.ini

Drop EOL Python 3.7 and Django 2.2.
Add Python 3.12 and Django 5.0.
I looked back at #1264 to figure out the changes required.

Update supported versions, remove eol dj22 and py37, add dj5 and py12

---

tests/test_application_views.py
tests/test_auth_backends.py
tests/test_authorization_code.py
tests/test_client_credential.py
tests/test_decorators.py
tests/test_hybrid.py
tests/test_implicit.py
tests/test_introspection_auth.py
tests/test_introspection_view.py
tests/test_models.py
tests/test_oauth2_backends.py
tests/test_oauth2_validators.py
tests/test_password.py
tests/test_rest_framework.py
tests/test_scopes.py
tests/test_token_endpoint_cors.py
tests/test_token_revocation.py
tests/test_token_view.py

Speed up the test suite to be about twice as fast, using these techniques:
1. Move model creation into `setUpTestData()`, so it runs only once per test case. See [my post](https://adamj.eu/tech/2021/04/12/how-to-convert-a-testcase-from-setup-to-setuptestdata/).
2. Remove `tearDown()` methods that removed model instances. These were always unnecessary as Django resets the database for you.
3. Move immutable `RequestFactory`s to class-level variables.
Measuring on the Python 3.12 and Django 5.0 environment (added in #1350), I got 207s before these changes and 105s afterwards, approximately twice as fast.

Speed up tests ~2x

---

CHANGELOG.md

Add changelog entry for Django 4.2 support

---

docs/rest-framework/getting_started.rst

Fixes #
Added `LOGIN_URL = '/admin/login/'` to the `settings.py` in DOT tutorial for Django REST Framework. Without this, hitting `http://localhost:8000/o/applications/` redirects to URL not found error page.

Add LOGIN_URL settings in getting_started.rst

---

AUTHORS
CHANGELOG.md
oauth2_provider/settings.py

Hi :wave: , I believe this is causing us a problem, but I lack technical rigor to be able to explain it fully. By applying this change under certain circumstances, I seem to avoid a core dump that happens as uWSGI recycles workers when it is running in the default prefork mode. The most relevant description of the series of events is this comment: https://github.com/unbit/uwsgi/issues/1969#issuecomment-462252471
Here, I just wish to present this as an improvement to follow best practice. In the `django.test.signals` module, you can see it imports from this modification with no modifications.
https://github.com/django/django/blob/main/django/test/signals.py
However, somewhat obviously... if you import this test _module_, you will also register all the test signal connections. Now, that …

Move signal import to django.core

---

AUTHORS
CHANGELOG.md
oauth2_provider/views/oidc.py
tests/test_oidc_views.py

Fixes #1249
Some OIDC clients require code_challenge_methods_supported to be present in auto discovery information. The PR adds this property to ConnectDiscoveryInfoView.

Add code_challenge_methods_supported property to OIDC auto discovery

---

AUTHORS
CHANGELOG.md
oauth2_provider/views/base.py
tests/app/idp/idp/oauth.py
tests/app/idp/idp/settings.py
tests/test_authorization_code.py

Fixes #1268
Fix bug preventing support for Silent Authentication. If an unauthorized request to `AuthorizationView` with a query parameter that contains `prompt=none` happens, then we will redirect with an error code of `login_required` otherwise everything will proceed as before. 
See https://auth0.com/docs/authenticate/login/configure-silent-authentication#error-responses
and https://openid.net/specs/openid-connect-core-1_0.html#AuthError
fully supporting prompt=none will require implementing validate_silent_login in the validator. this doesn't implement that, but will allow people to implement it if they want until we can implement a good implementation for DOT.

fix: prompt=none shows a login screen

---

docs/index.rst

I simply copy pasted the ones from the [README.rst](https://github.com/jazzband/django-oauth-toolkit/blob/master/README.rst)

Update index.rst requirements

---

docs/oidc.rst

Just a small typo fix. If users copy the example module reference from below they can avoid the import error if the file is named correctly.

Update oidc.rst: match example file name to import

---

docs/advanced_topics.rst
docs/contributing.rst
docs/getting_started.rst
docs/install.rst
docs/management_commands.rst
docs/rest-framework/getting_started.rst
docs/settings.rst
docs/signals.rst
docs/tutorial/tutorial_01.rst
docs/tutorial/tutorial_02.rst
docs/tutorial/tutorial_03.rst
docs/tutorial/tutorial_04.rst
docs/tutorial/tutorial_05.rst
docs/views/application.rst
docs/views/class_based.rst
docs/views/function_based.rst
docs/views/token.rst

Hello, I've read through all the documentation pages and refactored them to have consistent markups. Also, fixed several errors during the proofreading.
All changes are documentation clean up so I combined the same kind of changes into each commit, but if you feel this PR contains too many changes, I can split this PR into small chunks. 🙂 
- [x documentation updated
- [N/A] `CHANGELOG.md` updated (only for user relevant changes)

docs: clean up and improve documentation

---

oauth2_provider/views/token.py

Hi, this is a just small typo fix in one method docstring.

docs: fix a tiny typo in method docstring

---

.pre-commit-config.yaml
AUTHORS
CHANGELOG.md
docs/getting_started.rst
docs/oidc.rst
docs/tutorial/tutorial_01.rst
docs/tutorial/tutorial_04.rst
oauth2_provider/contrib/rest_framework/permissions.py
oauth2_provider/oauth2_validators.py
oauth2_provider/views/base.py
pyproject.toml
tests/app/idp/idp/oauth.py
tests/mig_settings.py
tests/test_implicit.py

https://github.com/codespell-project/codespell is great to catch typos
Let me know if needs changelog entry etc

Add codespell support: config + workflow to catch new typos, let it fix some

---

docs/oidc.rst

According to [urls.py](https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/urls.py#L45), the url should be /logout

Update url for RP initiated logout

---

docs/oidc.rst
docs/settings.rst

Document OIDC_ENABLED in settings.rst

---

tox.ini

Replace [deprecated](https://github.com/tox-dev/tox/pull/2600) `whitelist_external` with `allowlist_external`

tox.ini whitelist -> allowlist

---

AUTHORS
docs/tutorial/tutorial_05.rst

**Fixes #1421**
The code snippet provided in the documentation needs an additional import to function correctly. Without this import, the code does not raise any errors, but it fails to discover `@shared_task`s in other files. This PR adds the necessary import statement.
**Link to Documentation:** [Django OAuth Toolkit Tutorial - Step 5](https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_05.html)

1421 missing import in documentation

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml

pre-commit is raising code spell errors 
- ignore AUTHORS- we don't need to spell check names Savin was raising an error
- fix misspelling of compatibility in CHANGELOG.md
- ignore assertIn from the python unittest library.

chore: fix code spell errors

---

.dockerignore
Dockerfile
docker-compose.yml
tests/app/idp/idp/settings.py
tests/app/idp/requirements.txt
tests/app/rp/Dockerfile
tests/app/rp/package-lock.json
tests/app/rp/package.json
tests/app/rp/svelte.config.js

- add Dockerfile to build the tests/app/idp
- add Dockerfile to build the tests/app/rp
- add a docker compose file to build and start instances of the idp and rp
You can test this setup with
```docker-compose up```
This could be nice for testing new branches with the following
```
docker-compose down -v # remove existing env
docker-compose build      # rebuild the images
docker-compose up          # spin up the docker  compose environment
```
You should be able to goto http://localhost:5173 and http://localhost:8000 to access the compose instances. 
This is a precursor to publishing the test IDP as a container via docker hub. I hope making a Django based IDP more accessible will help grow our contributor and user community. 
- [N/A ] unit-test added
I wasn't quite sure where or how to …

feat: containerized apps

---

README.rst

I noticed that the installation section in the README was using single backticks (\`) instead of double backticks (\`\`) to mark up some code. This works in Markdown, but doesn't really work in reStructuredText. While I was there I also tagged `urls.py`.

Correct rst syntax in installation section

---

docs/install.rst

Removed the bit about using `re_path` to add urls. It's just confusing, as a user I don't know why I should pick this option over the first one.

Drop re_path from installation guide

---

AUTHORS
README.rst
docs/getting_started.rst
docs/install.rst
docs/rest-framework/getting_started.rst
docs/tutorial/tutorial_01.rst
tests/urls.py

Simplify how urlpatterns are loaded, as requested in https://github.com/jazzband/django-oauth-toolkit/pull/1435#pullrequestreview-2131162185

Simplify urlpattern loading

---

AUTHORS
CHANGELOG.md
oauth2_provider/contrib/rest_framework/authentication.py
tests/test_rest_framework.py

Fixes #1443
This PR applies a similar set of changes as #963 except for the Django Rest Framework contrib extension. I've tried my best to add tests for this case as well, but if there's anything else I'm missing please let me know!

Handle invalid hex values in query strings in DRF extension

---

.github/workflows/test.yml
CHANGELOG.md
README.rst
docs/index.rst
setup.cfg
tox.ini

Django versions below 4.2 are no longer supported, so this PR removes mentions and CI for these versions.

drop support for Django versions below 4.2

---

.github/workflows/lint.yaml
.gitignore
.pre-commit-config.yaml
pyproject.toml
tox.ini

Format check using Ruff in separate job, because it doesn't depend on neither  Python nor Django versions. I'm planning to replace isort and flake8 with Ruff in coming days.

check format using ruff

---

setup.cfg
tox.ini

Pytz should be an optional dependency.

Make pytz optional

---

.github/workflows/lint.yaml
.pre-commit-config.yaml
docs/contributing.rst
pyproject.toml
tox.ini

This PR replaces isort with ruff, already introduced in https://github.com/jazzband/django-oauth-toolkit/pull/1457 for format checking.
`I` enables isort and `Q` enables flake8-quotes rules.
```toml
[tool.ruff.lint]
select = ["I", "Q"]
```

replace isort with ruff

---

.github/workflows/lint.yaml
.github/workflows/release.yml
.github/workflows/test.yml

This PR bumps actions/setup-python to v5, and fixes below warning.
> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/setup-python@v4. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

CI: bump actions/setup-python to v5

---

.pre-commit-config.yaml
docs/contributing.rst
pyproject.toml
tox.ini

This PR replaces flake8 with ruff, and enables following rules.
- E, W - pycodestyle
- F - pyflakes
Run ```tox -e lint``` to test the changes.

replace flake8 with ruff

---

pyproject.toml
tox.ini

I found that configurations of tools split into pyproject.toml and tox.ini, thus confusing. This PR centralizes all tools configuration into pyproject.toml.

centralize tools config in pyproject.toml

---

CHANGELOG.md
README.rst
docs/index.rst
docs/requirements.txt
pyproject.toml
tox.ini

This PR bumps oauthlib version to 3.2, which was releases in 2022.

bump oauthlib to 3.2

---

CHANGELOG.md
oauth2_provider/views/base.py
tests/test_ui_locales.py

Fixes #1468
Makes sure `credential["ui_locales"] is a string before passing it to `oauthlib`.
`oauthlib` always calls `split` on the values of `ui_locales`:
https://github.com/oauthlib/oauthlib/blob/d319c54ae0342d9a2596ef7afa1e17984c303550/oauthlib/openid/connect/core/grant_types/base.py#L317
The way django-oauth-toolkit is structured the `credentials` dictionary contains the value of `ui_locales` as processed by `oauthlib`, which makes it a list. It is then passed back into `oauthlib` which tries to parse it again, resulting in an `AttributeError`.
`oauthlib` is a bit more careful with the way it handles the `prompt` parameter:
https://github.com/oauthlib/oauthlib/blob/d319c54ae0342d9a2596ef7afa1e17984c303550/oauthlib/openid/connect/core/grant_types/base.py#L289-L292
So this might be a …

Work around double parsing of ui_locales

---

AUTHORS
CHANGELOG.md
oauth2_provider/oauth2_validators.py
tests/test_oauth2_validators.py

This change raises an `InvalidGrantError` from the `OAuth2Validator.invalidate_authorization_code` method if the Grant object intended to be deleted does not exist.
Currently, when invalidating an authorization code after it has been used, if for whatever reason the associated grant object no longer exists, an uncaught `Grant.DoesNotExist` exception is raised. This leads to 500 responses being returned to clients. This could, for example, be caused by concurrent requests being made using the same authorization code.
The change in this PR handles this scenario gracefully by catching `Grant.DoesNotExist` and raising an `InvalidGrantError` which will return a 400 'invalid_grant' response to the client.

Raise InvalidGrantError if no associated grant exists when invalidating an authorization code

---

CHANGELOG.md
README.rst
docs/index.rst
docs/requirements.txt
pyproject.toml
tox.ini

Fixes https://github.com/jazzband/django-oauth-toolkit/issues/1478
(Almost) copy/pasta of https://github.com/jazzband/django-oauth-toolkit/pull/1465.
This PR bumps oauthlib version to 3.2.2, which was releases in early 2023 to address a [CVE](https://github.com/advisories/GHSA-3pgj-pg6c-r5p7)

bump oauthlib to 3.2.2

---

tests/test_commands.py

Fixes #1482
Older Django has one error message that the failure test was looking for. Newer Django (main branch) has a different error message, so check for both.

Fix test for changed error message from newer Django (djmain)

---

tests/test_oauth2_validators.py

Fixes #1497 unrelated tox failures
The test mocked validation endpoint sometimes returns a 404 or a 405. It's not clear where this changed
but it first appeared in #1497 which was unrelated.
It turns out the test neglected to mock the POST endpoint so the POST was being sent to the live example.com website. Apparently example.com changed their response from a 404 to a 405.
The fix mocks the endpoint to always return a 404 Not Found.

deal with 404 or 405 validator error

---

.env
.vscode/settings.json
docs/contributing.rst
pyproject.toml

Implement configuration for interactive debugging in VS Code. 

feat: VS Code Testing Activity Support

---

AUTHORS
CHANGELOG.md
docs/settings.rst
oauth2_provider/models.py
oauth2_provider/settings.py
tests/custom_hasher.py
tests/settings.py
tests/test_models.py

With every Django version PBKDF2 password hasher gets iterations increased and the next one will be set to 1 mio.
This poses a problem in our case because it affects the performance of /token endpoint. We whitelist to the IPs from which endpoint is accessible so we want to use weaker algorithm. For normal UI login we still want to retain default one.
Added a setting for specifying client server hasher using CLIENT_SECRET_HASHER.

Support for specifying client secret hasher

---

CHANGELOG.md
docs/settings.rst
oauth2_provider/models.py
oauth2_provider/settings.py
oauth2_provider/validators.py
tests/test_application_views.py
tests/test_models.py
tests/test_validators.py

Fixes #1506 
Implement Wildcard support in allowed origins and redirect uris

feat: allowed_origin and redirect_uri wildcards

---

oauth2_provider/views/base.py

The client_secret is posted to the token endpoint when using the client_credentials grant.
(sorry just a basic drive-by PR because I noticed this while debugging something else)

Add client_secret to sensitive_post_parameters

---

.github/workflows/test.yml

Bump github to `setup-node@v4` from v2.

bump to actions/setup-node@v4

---

.github/workflows/test.yml

This PR bumps actions/cache to v4, fixes depreciation warnings

Bump actions/cache to v4

---

CHANGELOG.md
oauth2_provider/views/oidc.py
tests/test_oidc_views.py

The OAuth provider is prompting users who no longer have an user session with the OAuth Provider to logout of the OP. This happens in scenarios given the user has logged out of the OP directly or via another client. In cases where the user does not have a session on the OP we should not prompt them to log out of the OP as there is no session, but we should still clear out their tokens to terminate the session for the Application.
I also renamed a test that used expired_session in the name to without_op_session. I believe that was their original intent, @tonial can you confirm?

fix: OP prompts for logout when no OP session

---

AUTHORS
CHANGELOG.md
oauth2_provider/migrations/0012_add_token_checksum.py

Fixes #1521
This PR uses `.iterator()` instead of `.all()` in the `0012_add_token_checksum` migration to prevent reading the whole table into memory.
I'm not sure if it makes sense to unittest this.

Use iterator in access token migration

---

tests/app/idp/requirements.txt

Fixes #
Running `docker-compose build` fails at the moment due to a package resolution conflict. Allowing to use Django 4.2 solves the issue.

Fix range of allowed django versions

---

CHANGELOG.md
Dockerfile
docs/contributing.rst

Fixes #1584
Copy the static files and templates to the path that the IDP was expecting them to be at.

fix: idp image can't find templates or statics

---

docs/settings.rst

Previously, it was unclear that the swappable model settings should always be set without a namespace, as the sub-section titles didn't include the required `OAUTH2_PROVIDER_` prefix. The warning at the top may not be noticed by people looking for a specific settings, and it was still unclear given the sub-section titles.
Additionally, this documents the `OAUTH2_PROVIDER_ID_TOKEN_MODEL` and `OAUTH2_PROVIDER_GRANT_MODEL` settings, which were previously undocumented.
Also, this corrects a mistake where `ACCESS_TOKEN_GENERATOR` was mentioned as the setting which enables the use of `SettingsScopes`; the actual setting is `SCOPES_BACKEND_CLASS`.

Improve settings documentation

---

CHANGELOG.md
oauth2_provider/views/introspect.py
tests/test_introspection_view.py
tox.ini

Handle `AttributeError` in `get_token_response`. If there is no `token` parameter in introspect endpoints they raise `AttributeError`.

Fix: Handle AttributeError in IntrospectTokenView

---

docs/management_commands.rst

Hi mates, nothing major really, just a tiny [misleading permalink](https://django-oauth-toolkit.readthedocs.io/en/latest/management_commands.html#createapplication) I ran into today :slightly_smiling_face:

Move around Label Targets.
