django-oauth/django-oauth-toolkit

docs/tutorial/tutorial_02.rst
As not a django newbie, I check this for an hour. So hope it can be added.
=> Miss import django.HttpResponse.

oauth2_provider/tests/test_mixins.py, oauth2_provider/views/mixins.py
=> Let OPTIONS requests pass

oauth2_provider/middleware.py, oauth2_provider/tests/test_auth_backends.py
When `OAuth2TokenMiddleware` is used with django's `UpdateCacheMiddleware` and `FetchFromCacheMiddleware`, the response is cached independently of the access token validation.
For example: When the first request has a correct access token, the following requests will retrieve the same response, (Even when the `Authorization` header is removed from the request).
It would happen to a reverse proxy too, depending on its configuration.
This PR adds the `Authorization` to the `Vary` header in the `OAuth2TokenMiddleware`. So that the django cache middleware (or a reverse proxy) can use the `Authorization` header in its cache key.
=> add 'Authorization' to 'Vary' header in the middleware

docs/tutorial/tutorial.rst, docs/tutorial/tutorial_04.rst
This is not at all exhaustive, but after running into the issue myself and seeing #217 (as well as the questions in #244, I thought I'd write up what I learned!
This is by no means final, and I think can be improved, but just wanted to get it out there. Not sure if this lives best as a tutorial section, but that's how the docs seem organized for now.
=> First draft on revoke token write-up.

docs/tutorial/tutorial_03.rst
As discussed in https://github.com/evonove/django-oauth-toolkit/issues/295.
=> Fixing doc about SessionAuthenticationMiddleware

oauth2_provider/forms.py, oauth2_provider/tests/test_application_views.py, oauth2_provider/views/application.py
=> Application registration view uses custom application model in form class

docs/views/token.rst, docs/views/views.rst
=> added doc for token views

AUTHORS, README.rst, docs/changelog.rst, oauth2_provider/migrations/0003_auto_20160316_1503.py, oauth2_provider/models.py
This is an attempt at solving Issue #357 
I would still like to review if there are any code paths that assume `User` is always filled in.
Also, I am not sure if migrations need special treatment if they are based on a swappable model... any advice here by anyone is appreciated.
=> Nullable Users

docs/rest-framework/permissions.rst
=> docs: permissions: Typo

oauth2_provider/migrations/0001_initial.py, oauth2_provider/migrations/0002_08_updates.py, oauth2_provider/migrations/0003_auto_20160316_1503.py, oauth2_provider/models.py
This fixes most Django 2.0 warnings.
=> Add on_delete to all ForeignKey and OneToOne fields

oauth2_provider/views/base.py
Hey there! Just wanted to reach out and say this library is super awesome and useful. Thanks for creating it! When I was trying to figure out how AuthorizationView worked I noticed that there were some typos in the docstring, so I figured I would fix them.
Thanks again!
=> Fix three typos

README.rst, docs/advanced_topics.rst
This documents the feature added in #448.
=> Added documentation for AbstractApplication.allows_grant_type

docs/settings.rst
=> Add missing SCOPES_BACKEND_CLASS default  to docs

docs/tutorial/tutorial_02.rst
Sorry if I'm not following your process perfectly, I just noticed a small grammatical error in the documentation, and wanted to fix it. Let me know if you need any more info.
=> Small grammatical change in tutorial_02.rst

docs/rest-framework/getting_started.rst
Modified the example code so it now works Django 2.0.3 and Django REST Framework 3.7.7
=> Updates to get example code to work with latest Django and DRF

docs/rest-framework/getting_started.rst
Apologies, in my previous PR some errors were introduced when I was interweaving my changes to the existing sample code. This time I have deleted the existing sample code and copied in my working code for Django 2.0.3 and DRF 3.7.7.
=> Further update to DRF example.

docs/advanced_topics.rst, docs/rest-framework/permissions.rst
fixed some grammar and spelling issues while reading the Django rest framework portion of the DOT docs.
=> fix permissions.rst grammar and spelling

docs/rest-framework/getting_started.rst
Update DRF sample code to support getting a User instance and
also creating a new User.
=> Add support for detail and create views in DRF sample code

oauth2_provider/oauth2_validators.py, tests/test_oauth2_validators.py
fix for the issue mentioned in [591](https://github.com/jazzband/django-oauth-toolkit/issues/591)
=> try except block for ValueError added with tests

oauth2_provider/oauth2_validators.py
Seems to fix the many issues I have in production
The green step does the trick
Code to generate the diagram [here](https://gist.github.com/gbataille/28573bf1ac4aca95e53351aa0056ff0a)
=> fix(#638): concurrency issue on new token from refresh token

oauth2_provider/oauth2_validators.py
=> Cherry pick #639

.travis.yml, tox.ini
=> Update Travis testing matrix

.travis.yml
Travis removed support `sudo: false` some time ago
=> Remove deprecated option in tests

docs/rest-framework/getting_started.rst
Added additional documentation for using the refresh token (issue #635 )
=> Added documentation for using request token in Getting Started

docs/tutorial/tutorial_01.rst
I am pretty new to Django and came across to problem mentioned in  #121 . I thought it would be good to add warning for this to docs.
=> add login warning for application registration to docs

oauth2_provider/management/commands/createapplication.py, tests/test_commands.py
=> Added management command to create applications

oauth2_provider/oauth2_validators.py, tests/test_authorization_code.py, tests/test_client_credential.py, tests/test_implicit.py, tests/test_introspection_auth.py, tests/test_introspection_view.py, tests/test_password.py, tests/test_scopes.py, tests/test_token_revocation.py, tests/test_token_view.py
Reopen #747 which was closed by mistake after a bad rebase.
=> Use Model.objects.create where applicable

docs/changelog.rst
Hi,
I noticed the changelog on read the docs was outdated, so I updated it with the last information from github, I guess this can be useful to someone.
Let me know if something else is required for this PR.
Lionel
=> Update changelogs in the docs with last information from github changelog

tests/utils.py
=> Fix simple typo: containg -> containing

oauth2_provider/views/base.py, tests/test_authorization_code.py
Reverts jazzband/django-oauth-toolkit#754
=> Revert "Auto-authorize if valid refresh tokens exist"

CHANGELOG.md, setup.cfg
=> release 1.3.0

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Fixes #
Add some issue templates to aid in triage.
=> add some issue templates

CHANGELOG.md
=> Add changelog for PR #810

CHANGELOG.md, setup.cfg
=> Release 1.3.1

tests/test_authorization_code.py, tests/test_implicit.py
remove unnecessary urlencode use and make tests more readable.
=> remove urlencode in tests

oauth2_provider/urls.py
=> use re_path

AUTHORS, CHANGELOG.md, oauth2_provider/views/introspect.py, tests/test_introspection_view.py
Fixes #
Just added select_related() for optimization
=> select_related added to introspect view

oauth2_provider/models.py
=> Documentation update for issue #856

setup.cfg
Fixes #878
Update version to 1.3.3
=> release 1.3.3

tests/models.py, tests/test_application_views.py, tests/test_auth_backends.py, tests/test_client_credential.py, tests/test_decorators.py, tests/test_mixins.py
Updated `super()` calls, no longer need to pass in args.
=> Updated super()

.travis.yml, CHANGELOG.md, docs/index.rst, setup.cfg, tox.ini
=> Updated supported Django versions

docs/models.rst
Single quotes are italics in reST and I see no need for them in this particular heading.
- [n/a] unit-test added
- [n/a] `CHANGELOG.md` updated (only for user relevant changes)
- [n/a] author name in `AUTHORS`
=> Remove italics from "Models" section header

docs/oidc.rst
=> doc: missing argument to get_userinfo_claims

AUTHORS, oauth2_provider/locale/fa/LC_MESSAGES/django.po
Fixes #
Add Farsi(persian) language support.
=> Add Farsi/fa language support

docs/getting_started.rst
Documentation grammar: "... you call /token/ endpoint direct" -> "... you call /token/ endpoint *directly*"
=> Documentation grammar

setup.cfg
=> six should be dropped

oauth2_provider/__init__.py
=> Bump version: 1.5.0 → 1.6.0

CHANGELOG.md, oauth2_provider/__init__.py
=> Release 1.7.0

README.rst
Per https://github.com/orgs/jazzband/teams/django-oauth-toolkit/discussions/5 adds help wanted info to the README.
=> Add help wanted to the README

CHANGELOG.md, oauth2_provider/locale/fr/LC_MESSAGES/django.po
Fixes #
I have added the french translation file.
=> Adds french translation file

docs/getting_started.rst
Added encode 'utf-8' for code_verifier
Fixes #
=> Fixbug Type error a bytes-like

AUTHORS, docs/getting_started.rst
=> Hotfix 'Attribute error in generate code_challenge ex.'

AUTHORS, CHANGELOG.md, oauth2_provider/__init__.py
=> Release 2.2.0

docs/getting_started.rst
Fixes #
Type is changed from 'bellow' to 'below' in getting started guide.
=> typo for word 'bellow' fixed.

.github/workflows/release.yml, .github/workflows/test.yml
Upgrade actions versions and use Python 3.12 for the release workflow.
=> Upgrade GitHub Actions

docs/install.rst
Trivial documentation typo fix.
=> Add missing closing )

docs/getting_started.rst
Update getting_started.rst
Fixes #
=> Fixes typo
